ADH_DNA='atgGCTGTTACTAATGTCGCTGAACTTAACGCACTCGTAGAGCGTGTAAAAAAAGCCCAGCGTGAATATGCCAGTTTCACTCAAGAGCAAGTAGACAAAATCTTCCGCGCCGCCGCTCTGGCTGCTGCAGATGCTCGAATCCCACTCGCGAAAATGGCCGTTGCCGAATCCGGCATGGGTATCGTCGAAGATAAAGTGATCAAAAACCACTTTGCTTCTGAATATATCTACAACGCCTATAAAGATGAAAAAACCTGTGGTGTTCTGTCTGAAGACGACACTTTTGGTACCATCACTATCGCTGAACCAATCGGTATTATTTGCGGTATCGTTCCGACCACTAACCCGACTTCAACTGCTATCTTCAAATCGCTGATCAGTCTGAAGACCCGTAACGCCATTATCTTCTCCCCGCACCCGCGTGCAAAAGATGCCACCAACAAAGCGGCTGATATCGTTCTGCAGGCTGCTATCGCTGCCGGTGCTCCGAAAGATCTGATCGGCTGGATCGATCAACCTTCTGTTGAACTGTCTAACGCACTGATGCACCACCCAGACATCAACCTGATCCTCGCGACTGGTGGTCCGGGCATGGTTAAAGCCGCATACAGCTCCGGTAAACCAGCTATCGGTGTAGGCGCGGGCAACACTCCAGTTGTTATCGATGAAACTGCTGATATCAAACGTGCAGTTGCATCTGTACTGATGTCCAAAACCTTCGACAACGGCGTAATCTGTGCTTCTGAACAGTCTGTTGTTGTTGTTGACTCTGTTTATGACGCTGTACGTGAACGTTTTGCAACCCACGGCGGCTATCTGTTGCAGGGTAAAGAGCTGAAAGCTGTTCAGGATGTTATCCTGAAAAACGGTGCGCTGAACGCGGCTATCGTTGGTCAGCCAGCCTATAAAATTGCTGAACTGGCAGGCTTCTCTGTACCAGAAAACACCAAGATTCTGATCGGTGAAGTGACCGTTGTTGATGAAAGCGAACCGTTCGCACATGAAAAACTGTCCCCGACTCTGGCAATGTACCGCGCTAAAGATTTCGAAGACGCGGTAGAAAAAGCAGAGAAACTGGTTGCTATGGGCGGTATCGGTCATACCTCTTGCCTGTACACTGACCAGGATAACCAACCGGCTCGCGTTTCTTACTTCGGTCAGAAAATGAAAACGGCGCGTATCCTGATTAACACCCCAGCGTCTCAGGGTGGTATCGGTGACCTGTATAACTTCAAACTCGCACCTTCCCTGACTCTGGGTTGTGGTTCTTGGGGTGGTAACTCCATCTCTGAAAACGTTGGTCCGAAACACCTGATCAACAAGAAAACCGTTGCTAAGCGAGCTGAAAACATGTTGTGGCACAAACTTCCGAAATCTATCTACTTCCGCCGTGGCTCCCTGCCAATCGCGCTGGATGAAGTGATTACTGATGGCCACAAACGTGCGCTCATCGTGACTGACCGCTTCCTGTTCAACAATGGTTATGCTGATCAGATCACTTCCGTACTGAAAGCAGCAGGCGTTGAAACTGAAGTCTTCTTCGAAGTAGAAGCGGACCCGACCCTGAGCATCGTTCGTAAAGGTGCAGAACTGGCAAACTCCTTCAAACCAGACGTGATTATCGCGCTGGGTGGTGGTTCCCCGATGGACGCCGCGAAGATCATGTGGGTTATGTACGAACATCCGGAAACTCACTTCGAAGAGCTGGCGCTGCGCTTTATGGATATCCGTAAACGTATCTACAAGTTCCCGAAAATGGGCGTGAAAGCGAAAATGATCGCTGTCACCACCACTTCTGGTACAGGTTCTGAAGTCACTCCGTTTGCGGTTGTAACTGACGACGCTACTGGTCAGAAATATCCGCTGGCAGACTATGCGCTGACTCCGGATATGGCGATTGTCGACGCCAACCTGGTTATGGACATGCCGAAGTCCCTGTGTGCTTTCGGTGGTCTGGACGCAGTAACTCACGCCATGGAAGCTTATGTTTCTGTACTGGCATCTGAGTTCTCTGATGGTCAGGCTCTGCAGGCACTGAAACTGCTGAAAGAATATCTGCCAGCGTCCTACCACGAAGGGTCTAAAAATCCGGTAGCGCGTGAACGTGTTCACAGTGCAGCGACTATCGCGGGTATCGCGTTTGCGAACGCCTTCCTGGGTGTATGTCACTCAATGGCGCACAAACTGGGTTCCCAGTTCCATATTCCGCACGGTCTGGCAAACGCCCTGCTGATTTGTAACGTTATTCGCTACAATGCGAACGACAACCCGACCAAGCAGACTGCATTCAGCCAGTATGACCGTCCGCAGGCTCGCCGTCGTTATGCTGAAATTGCCGACCACTTGGGTCTGAGCGCACCGGGCGACCGTACTGCTGCTAAGATCGAGAAACTGCTGGCATGGCTGGAAACGCTGAAAGCTGAACTGGGTATTCCGAAATCTATCCGTGAAGCTGGCGTTCAGGAAGCAGACTTCCTGGCGAACGTGGATAAACTGTCTGAAGATGCATTCGATGACCAGTGCACCGGCGCTAACCCGCGTTACCCGCTGATCTCCGAGCTGAAACAGATTCTGCTGGATACCTACTACGGTCGTGATTATGTAGAAGGTGAAACTGCAGCGAAGAAAGAAGCTGCTCCGGCTAAAGCTGAGAAAAAAGCGAAAAAATCCGCTtaa'

codontab = {
    'UCA': 'S',    # Serine
    'UCC': 'S',    # Serine
    'UCG': 'S',    # Serine
    'UCU': 'S',    # Serine
    'UUC': 'F',    # Phenylalanine
    'UUU': 'F',    # Phenylalanine
    'UUA': 'L',    # Leucine
    'UUG': 'L',    # Leucine
    'UAC': 'Y',    # Tyrosine
    'UAU': 'Y',    # Tyrosine
    'UAA': '*',    # Stop
    'UAG': '*',    # Stop
    'UGC': 'C',    # Cysteine
    'UGU': 'C',    # Cysteine
    'UGA': '*',    # Stop
    'UGG': 'W',    # Tryptophan
    'CUA': 'L',    # Leucine
    'CUC': 'L',    # Leucine
    'CUG': 'L',    # Leucine
    'CUU': 'L',    # Leucine
    'CCA': 'P',    # Proline
    'CCC': 'P',    # Proline
    'CCG': 'P',    # Proline
    'CCU': 'P',    # Proline
    'CAC': 'H',    # Histidine
    'CAU': 'H',    # Histidine
    'CAA': 'Q',    # Glutamine
    'CAG': 'Q',    # Glutamine
    'CGA': 'R',    # Arginine
    'CGC': 'R',    # Arginine
    'CGG': 'R',    # Arginine
    'CGU': 'R',    # Arginine
    'AUA': 'I',    # Isoleucine
    'AUC': 'I',    # Isoleucine
    'AUU': 'I',    # Isoleucine
    'AUG': 'M',    # Methionine
    'ACA': 'T',    # Threonine
    'ACC': 'T',    # Threonine
    'ACG': 'T',    # Threonine
    'ACU': 'T',    # Threonine
    'AAC': 'N',    # Asparagine
    'AAU': 'N',    # Asparagine
    'AAA': 'K',    # Lysine
    'AAG': 'K',    # Lysine
    'AGC': 'S',    # Serine
    'AGU': 'S',    # Serine
    'AGA': 'R',    # Arginine
    'AGG': 'R',    # Arginine
    'GUA': 'V',    # Valine
    'GUC': 'V',    # Valine
    'GUG': 'V',    # Valine
    'GUU': 'V',    # Valine
    'GCA': 'A',    # Alanine
    'GCC': 'A',    # Alanine
    'GCG': 'A',    # Alanine
    'GCU': 'A',    # Alanine
    'GAC': 'D',    # Aspartic acid
    'GAU': 'D',    # Aspartic acid
    'GAA': 'E',    # Glutamic acid
    'GAG': 'E',    # Glutamic acid
    'GGA': 'G',    # Glycine
    'GGC': 'G',    # Glycine
    'GGG': 'G',    # Glycine
    'GGU': 'G'     # Glycine
}

def transcription(sequence):
    sequence=sequence.upper()   #Alle buchstaben groß machen
    return(sequence.replace('T','U'))   #thymin wird durch uracil ersetzt
#print(transcription(ADH_DNA))

def translation(RNA):
    tss=RNA.find('AUG') #Start-Codon finden
    CDS=RNA[tss:]   #Zu-Translatierende RNA beginnt mit dem Start-Codon
    AA=str()    #Leerer String, in dem die AA-Sequenz aufgebaut wird
    while len(CDS)>=3:  #Solange noch mindestens ein ganzes Codon noch nicht translatiert wurde:
        codon=CDS[:3]   #Codon sind die ersten drei Basen
        if codontab[codon]=='*':    #Kontrolle: Ist es ein Stop-Codon?
            #print('STOP: '+codon)
            return(AA)  #Wenn ja: Bisherige AA-Sequenz zurückgeben
        else:
            AA=AA+codontab[codon]   #Die zum Codon-gehörende AA wird an die AA-Sequenz angehangen
            CDS=CDS[3:]     #Das aktuelle Codon wird aus der CDS entfernt, damit es mit dem nächsten Codon weitergeht
    return(AA)

print(translation(transcription(ADH_DNA)))
